spring:
    datasource:
        url: jdbc:mysql://${DEFAULT_HOST}:3306/${JDBC_DATABASE}?useSSL=false&useTimezone=true&serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false&characterEncoding=UTF-8
        username: ${JDBC_USER}
        password: ${JDBC_PASS}
        hikari:
            validation-timeout: 3000
            connection-timeout: 20000
            connection-test-query: SELECT 1
            minimum-idle: 1
            maximum-pool-size: 2
            max-lifetime: 30000
